### PR TITLE
Do not hardcode serviceMonitor / Service name

### PR DESCRIPTION
**Pull request by eyenx**
ServiceMonitor or Servicenames of the ADC Exporter shouldn't be hardcoded. Having more then one Citrix Ingress Controller in the same namespace doesn't work if we keep the same name for the adc exporter services.

Also add option additionalLabels to ServiceMonitor to be able to select it with prometheus.

### CODE REVIEW

**Comment by eyenx** [comment]
Fixed the rest of the file's indentation and also switched the `rbac.yaml` apiVersion to v1 as `helm lint` was giving me:

```
==> Linting .
[ERROR] templates/rbac.yaml: the kind "rbac.authorization.k8s.io/v1beta1 ClusterRole" is deprecated in favor of "rbac.authorization.k8s.io/v1 ClusterRole"

Error: 1 chart(s) linted, 1 chart(s) failed
```

**Comment by eyenx** [comment]
Any update @priyankash-citrix ?

**Comment by ankits123** [comment]
@eyenx We are already considering and working on it along with other related changes. It will be part of future release.

**Comment by eyenx** [comment]
I'll close this as nothing ever happened here. I'll recreate one or more PR, as I saw from new releases, the Service is still hardcoded... :-1:

**Pull request closed without merging**
